language: node_js
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - librsvg2-dev
      - g++-4.9
node_js:
- stable
cache:
  directories:
  - node_modules
before_install:
- npm install hexo-cli -g
install:
- npm install
before_script:
- git clone --single-branch -b source https://github.com/mr-cn/blog.git source
script:
- hexo clean
- hexo generate
after_script:
  - cd ./public
  - git init
  - git config user.name "mr"
  - git config user.email "admin@mr-cn.net"
  - git add .
  - git commit -m "TravisCI 自动部署"
  # Coding Pages
  - git push --force --quiet "https://mr-cn:${CO_TOKEN}@${CO_REF}" master:master

branches:
  only:
  - source
  - master

env:
 global:
   # Coding Pages
   - CO_REF: git.coding.net/mr-cn/mrcn_blog.git
   - CXX=g++-4.9